### PR TITLE
Option for setting the docutils writer part

### PR DESCRIPTION
**Pull request by uyar**
This is a complementary PR for #201. Different docutils writers produce different parts. Currently the extension always uses the `html_body` part of the writer output. Sometimes it might be needed to use a different part, such as `whole` (for example in order to include assets such as stylesheets). This PR adds a configuration setting for selecting the writer part to be used and sets the currently used `html_body` as the default.

### CODE REVIEW

**Comment by lextm** [comment]
Due to recent changes this pull request needs to be updated to resolve the conflicts.

Can you do that in the coming days?

**Comment by uyar** [comment]
I guess so. I'll look into it tomorrow.

**Comment by uyar** [comment]
I didn't get any conflicts on merge and it works fine on my Linux machine after running `npm compile` again. I don't know where the Azure errors are coming from. Can you give me any pointers?

**Comment by lextm** [comment]
Never mind. Let me merge it now and see if I can resolve the CI failures afterward. Thanks for the contribution.

**Pull request merged**
