### PR TITLE
Add configOverrides option

### PR DESCRIPTION
**Pull request by larsoner**
With this PR and adding to my `settings.json`:
```
"esbonio.sphinx.configOverrides": {"plot_gallery": false},
```
It fixes the problem @drammock described in #394 for me at least (we work on the same project so I was having the same issue :) ).

### CODE REVIEW

**Comment by larsoner** [comment]
... note that I didn't make this PR close that issue because this is just a workaround to make `sphinx-gallery` (which gets called during config-init) take seconds rather than hours to complete.

**Comment by larsoner** [comment]
@lextm any thoughts on this one yay/nay? To me the `restructuredtext` extension isn't super useful without this sort of thing because windows pop up endlessly on the projects I work on :(

**Comment by lextm** [comment]
190.1.x already contains this.

**Comment by drammock** [comment]
great!  When will 190.x be released?  Latest release seems to be 189.3 about 4 months ago.  If it's really fixed then #394 can be closed too I guess

**Comment by lextm** [comment]
190.1.x has been previewed for a few months now. The final release might take another couple of months, as the new preview engine needs further tuning.

**Comment by larsoner** [comment]
> 190.1.x has been previewed for a few months now

Indeed, going into vscode I was able to go to the `reStructuredText` extension page inside vscode and tell it to use the experimental version, which fixed my problem (when I added `"esbonio.sphinx.configOverrides": {"plot_gallery": false},` to my `settings.json`) -- thanks!

**Pull request closed without merging**
