### PR TITLE
Feature robotframework snippets

### PR DESCRIPTION
**Pull request by vairamsvsjdo**
Includes code snippets for robot framework https://github.com/robotframework/robotframework that supports reStructuredText as a test file format.

Please suggest how to target these snippets to be available only for ".. code:: robotframework" block

### CODE REVIEW

**Comment by lextm** [comment]
Thanks for sharing this. But this extension tries to be generic, so including such framework specific snippets is quite suitable.

You can write your own extension for robot framework, and let it depend on this extension. See "extensionDependencies" in [this page](https://code.visualstudio.com/docs/extensionAPI/extension-manifest) for details.

**Comment by vairamsvsjdo** [comment]
@lextm That is a good suggestion. Will do appropriately.

**Comment by lextm** [comment]
Let me know if you need any help on that extension. Once you finish, I can add it to the related section in this extension's page to promote it.

**Comment by vairamsvsjdo** [comment]
https://github.com/JayDevOps/vscode-robotframeworksnippets
@lextm  I  am having trouble enabling the snippets. The snippets added through the new extension is not showing up.

**Pull request closed without merging**
