### PR TITLE
new feature: support preview single RST file directly

### PR DESCRIPTION
**Pull request by jiezh**
Add sphinx config auto generation to support preview single rst file.

### CODE REVIEW

**Comment by lextm** [comment]
Thanks for the contribution. It is definitely useful.

I guess we should wait till #59 is implemented. Then this pull request can serve as the fall back mechanism.

**Comment by Autoplectic** [comment]
I would certainly appreciate this feature. Sometimes I write one-off rst files, and would like the ability to preview them.

**Comment by TormodLandet** [comment]
An idea: when writing one-off RST files you are probably using plain RST syntax, not Sphinx, so just running `rst2html.py input.rst output.html` may be sufficient? You can also depend on the pip package rst2html5 to get more modern HTML, but for previewing the rst2html that comes with docutils (and will be installed if Sphinx is installed) should be good enough?

**Comment by lextm** [comment]
Thanks for suggesting the alternative preview.

#92 implemented this, so now I close this pull request.

**Pull request closed without merging**
