### PR TITLE
Add simple preview

### PR DESCRIPTION
**Pull request by denisvm**
Add an option to configure a simple reStructuredText renderer to make it easier to set up and preview files. In this option it will consume the tool's stdout.

### CODE REVIEW

**Comment by lextm** [comment]
Sounds like a merge of multiple extensions (there are other extensions doing the same). I will have to consider the pros and cons for a while. Thanks for sending the PR.

**Comment by denisvm** [comment]
Hello @lextm, I'm sorry, I didn't see other extensions for this. I just wanted an option to do a quick preview without requiring the whole Sphinx configured and running thus providing more performance on building a single file preview.

It would be better to have this processed directly from the extension without an external dependency, so it would be easier to implement #26 for instance. But this is a quick option to make sure you get a fast preview and don't even need to write a temporary file for it.

**Comment by lextm** [comment]
A summary of different extensions can be found in my blog post,

https://blog.lextudio.com/update-on-restructuredtext-and-visual-studio-code-1b23916c4c0f#.oc90tiniw

I personally prefer accuracy to speed.

**Comment by denisvm** [comment]
Great, I understand and agree with you. Accuracy is always important :)

I suggest using `rst2html5` that is installed with [Doctools](http://docutils.sourceforge.net/), which was created by the creator of reStructuredText format. Sphinx also depends on Doctools.

In this case I think it would be really nice to have the option to choose your renderer based on your needs, which also makes it easier for the user to use any tool they want as long as it outputs the HTML that should be previewed, making it more customisable.

Thanks for your feedback!

**Comment by lextm** [comment]
Thanks for suggesting the alternative preview. 

#92 implemented this, so now I close this pull request.

**Pull request closed without merging**
